name: build package and docker image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
    
    - name: Install wheel build package
      run: python3 -m pip install build
    - name: Build the wheel
      run: python -m build
      
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag hive-autocheck:$(date +%Y%m%d)
    - name: Save the Docker image to a file
      run: docker save -o ./hive-autocheck-image.tar.gz hive-autocheck:$(date +%Y%m%d)

    - name: Upload Docker image
      uses: actions/upload-artifact@v4
      with:
        name: hive-autocheck
        path: |
          ./hive-autocheck-image.tar.gz
          ./dist/*.whl
