name: build package and docker image

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: false
        default: 'warning'

jobs:

  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
    
    - name: Install wheel build package
      run: python3 -m pip install build
    - name: Build the wheel
      run: python3 -m build
      
    - name: Build the Docker image
      run: docker build . --file linux.Dockerfile --tag hive-autocheck:$(date +%Y%m%d)
    - name: Add latest Tag
      run: docker tag hive-autocheck:$(date +%Y%m%d) hive-autocheck:latest
    - name: Save the Docker image to a file
      run: docker save -o ./dist/hive-autocheck-image.tar.gz hive-autocheck:$(date +%Y%m%d) hive-autocheck:latest

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: hive-autocheck
        path: |
          ./dist/hive-autocheck-image.tar.gz
          ./dist/*.whl

#  build-windows:
#    runs-on: windows-2022
#    needs: [build-linux]

#    steps:
 #   - uses: actions/checkout@v4
 #   - uses: actions/download-artifact@v4
 #     with:
  #      name: hive-autocheck
  #      path: ./dist/
      
#    - name: Build the Docker image
 #     run: docker build . --file windows.Dockerfile --tag hive-autocheck-windows:$(date +%Y%m%d)
 #   - name: Add latest Tag
 #     run: docker tag hive-autocheck-windows:$(date +%Y%m%d) hive-autocheck-windows:latest
 #   - name: Save the Docker image to a file
#      run: docker save -o ./dist/hive-autocheck-windows-image.tar.gz hive-autocheck-windows:$(date +%Y%m%d) hive-autocheck-windows:latest

 #   - name: Upload Artifacts
#      uses: actions/upload-artifact@v4
 #     with:
   #     name: hive-autocheck-windows
    #    path: |
     #     ./dist/hive-autocheck-windows-image.tar.gz
      #    ./dist/*.whl
